#!/bin/sh

for i in `ghc-pkg list | grep -o '^[^ ][^:]*'`; do
  conffile=`ls -1 $i | grep "^$1"`
  if test -n "$conffile"; then
    dir=`grep '^library-dirs' "$i/$conffile" | cut -d ' ' -f 2-`
    for j in `find "$dir" -name "libHS$2*.so"`; do
      echo "$j"
    done
  fi
done
